### PR TITLE
feat: adds license file 'CC-BY-4.0.txt' in the corresponding director…

### PR DESCRIPTION
**Pull request by mknoopvw**
…y 'LICENSES'.

## Description
This pull requests adds the license file 'CC-BY-4.0.txt' in the corresponding directory 'LICENSES' in order to fulfill that release guideline: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by mknoopvw** [comment]
@SebastianBezold and @carslen hopefully this addition can be added to our upcoming release without too much issues.

**Comment by SebastianBezold** [comment]
> @SebastianBezold and @carslen hopefully this addition can be added to our upcoming release without too much issues. Thank you very much for your support!

HI @mknoopvw, no issue at all. But question for clarification: Are you planning to put any documentation under CC-BY-4.0? You only need to add the License, if you are planning to release parts of the repo under the CC-BY. 
AFAIK, the only file that has to go under CC-BY as agreed with our project leads is the Adoption View specific to KITs. 
You are of course free to also put other content under CC-BY, as long as the main repo License is still Apache-2.0. 
All code has to be licensed under Apache-2.0 and technical documentation is also usually licensed under Apache-2.0

/cc @AngelikaWittek

**Comment by mknoopvw** [comment]
Hello @SebastianBezold -- very good question!
I do not know. I just the TRG and obviously missed that this is optional.

Nonetheless, I would like to proceed as this cannot be missing later on then.

Thank you very much!

**Comment by mknoopvw** [comment]
Adjusted to aim at "develop" to use "develop" as source for tags for the release candidates.

**Comment by mknoopvw** [comment]
After reconsidering, I will close this PR as MIW currently does have artefacts requiring the CC-BY-license to be present.

**Pull request closed without merging**
