### PR TITLE
release: json ld context caching hotfix

### PR DESCRIPTION
**Pull request by DominikPinsel**
This PR merges develop to main, to trigger a new release. In this version the context caching is fixed, which we need in various environments.

### CODE REVIEW

**Review by borisuu — APPROVED** [review]

**Review by borisrizov-zf — APPROVED** [review]

**Comment by DominikPinsel** [comment]
@carslen Just a merge from develop to release :) When you have time it would be great if you could merge it for us.

**Review by pmoscode — APPROVED** [review]

**Comment by borisrizov-zf** [comment]
@carslen The split PRs were done on develop. The changelog holds all the PR ids which were merged into develop up until this point. Should @DominikPinsel add the list of previous PRs to the description?

**Comment by carslen** [comment]
This PR is a contribution from a fork. The PR is a "hole in one" PR, containing different things like changes to 
- GH workflows
- Helm Chart
- Documentation
- source code 

Each of these could have been seperate PRs to the upstream. We're trying to encourage every dev team to open smaller PRs but open PRs more often. In the end you'll gain speed and less discussions. 

As it contains more than 1000 lines of changed code, I'm [forced to open an IP check](https://www.eclipse.org/projects/handbook/#ip-project-content) for this PR (there is also a TRG mentioning that). An IP-Check takes up to 2 weeks at Eclipse-Foundation. 

As you state that these changes are on develop, could we do a PR from develop → main inside eclipse-tractusx/managed-identity-wallet repo? Then we're working inside of the repo and no IP-Check is required.

**Comment by borisrizov-zf** [comment]
> This PR is a contribution from a fork. The PR is a "hole in one" PR, containing different things like changes to
> 
> * GH workflows
> * Helm Chart
> * Documentation
> * source code
> 
> Each of these could have been seperate PRs to the upstream. We're trying to encourage every dev team to open smaller PRs but open PRs more often. In the end you'll gain speed and less discussions.
> 
> As it contains more than 1000 lines of changed code, I'm [forced to open an IP check](https://www.eclipse.org/projects/handbook/#ip-project-content) for this PR (there is also a TRG mentioning that). An IP-Check takes up to 2 weeks at Eclipse-Foundation.
> 
> As you state that these changes are on develop, could we do a PR from develop → main inside eclipse-tractusx/managed-identity-wallet repo? Then we're working inside of the repo and no IP-Check is required.

Hi, sorry I didn't see it's a fork-PR. All of this should be on develop. @DominikPinsel please update the PR.

**Comment by DominikPinsel** [comment]
@borisrizov-zf @carslen  @pmoscode  New PR :) https://github.com/eclipse-tractusx/managed-identity-wallet/pull/123

**Pull request closed without merging**
