### PR TITLE
Fix/caching during tests

### PR DESCRIPTION
**Pull request by PManaras**
## Description
PR fixes issues due to throttling while resolving the contexts during JsonLd processing

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by borisrizov-zf** [comment]
@PManaras can you change the target branch to 'develop'

**Comment by DominikPinsel** [comment]
@PManaras This change should become obsolete once https://github.com/eclipse-tractusx/managed-identity-wallet/pull/100 is merged. The PR #100 introduces preloading of the most common contexts and should fix your issues. What do you think?

**Comment by borisrizov-zf** [comment]
I think we should merge this regardless of the fix, as it is useful to know that our tests won't cause a 24h block.

**Comment by DominikPinsel** [comment]
> I think we should merge this regardless of the fix, as it is useful to know that our tests won't cause a 24h block.

I see you point. On the other hand I'm not sure whether we really need two solutions fixing the same problem. I would only go with one solution. PR #100 solves the rate limit problem by introducing caching. The wiremock solution would need an update as soon as the MIW would introduces additional context (e.g. by introducing credential revocation).

I see that there might be a requirement for the tests to don't do any web calls at all. But in this case I would also introduce this functionality in the application itself, not only in the test scope (as done in PR #100).

**Review by borisrizov-zf — APPROVED** [review]

**Comment by borisrizov-zf** [comment]
@PManaras can you rebase, as we've merged a fix for the failing pipeline. I'll merge afterwards.

**Comment by borisrizov-zf** [comment]
@PManaras ping for rebase.

**Review by DominikPinsel — APPROVED** [review]

**Comment by borisrizov-zf** [comment]
Closing due to inactivity, feel free to reopen after a rebase.

**Pull request closed without merging**
