### PR TITLE
feat: initial revocation service added

### PR DESCRIPTION
**Pull request by nitin-vavdiya**
## Description

A verifiable credential revocation service is added. 
This is a reference implementation of  [Verifiable Credentials Status List v2021](https://www.w3.org/TR/2023/WD-vc-status-list-20230427/)
### Why

In the current application implementation, we cannot issue credentials that can be revoked.

### What

Revocation service added to support revocable credentials. 
The issuer can revoke an issued credential and check the revocation status of issued credentials. 

This is ref. implementation of [Verifiable Credentials Status List v2021](https://www.w3.org/TR/2023/WD-vc-status-list-20230427/)

This is originally developed at Cofinity-X 

Thanks, @mustafasalfiti  and @pmanaras for initial contribution.

Ref: 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by borisrizov-zf** [comment]
Merged #318, you'll need to rebase at some point.

**Review by evegufy — CHANGES_REQUESTED** [review]
Hi @nitin-vavdiya 
did you notice that the contribution https://github.com/eclipse-tractusx/managed-identity-wallet/pull/317 is much to huge? (max. 1,000 lines of content (including documentation, code, configuration files, and other forms of source code, see https://www.eclipse.org/projects/handbook/#ip-project-content). I don't think it's reasonable that someone would be able to review such a huge PR.

**Comment by nitin-vavdiya** [comment]
> Hi @nitin-vavdiya did you notice that the contribution #317 is much to huge? (max. 1,000 lines of content (including documentation, code, configuration files, and other forms of source code, see https://www.eclipse.org/projects/handbook/#ip-project-content). I don't think it's reasonable that someone would be able to review such a huge PR.



> Hi @nitin-vavdiya did you notice that the contribution #317 is much to huge? (max. 1,000 lines of content (including documentation, code, configuration files, and other forms of source code, see https://www.eclipse.org/projects/handbook/#ip-project-content). I don't think it's reasonable that someone would be able to review such a huge PR.

Yes, this is a huge PR as this contains the entire revocation application(APIs, test cases, docs etc) if we push partial changes then the test/checks will not pass or not meet the TRGs(specially document and chart related)
We need an IP review/check for this PR.

**Comment by evegufy** [comment]
> > Hi @nitin-vavdiya did you notice that the contribution #317 is much to huge? (max. 1,000 lines of content (including documentation, code, configuration files, and other forms of source code, see https://www.eclipse.org/projects/handbook/#ip-project-content). I don't think it's reasonable that someone would be able to review such a huge PR.
> 
> > Hi @nitin-vavdiya did you notice that the contribution #317 is much to huge? (max. 1,000 lines of content (including documentation, code, configuration files, and other forms of source code, see https://www.eclipse.org/projects/handbook/#ip-project-content). I don't think it's reasonable that someone would be able to review such a huge PR.
> 
> Yes, this is a huge PR as this contains the entire revocation application(APIs, test cases, docs etc) if we push partial changes then the test/checks will not pass or not meet the TRGs(specially document and chart related) We need an IP review/check for this PR.

Hi @nitin-vavdiya very good that you're aware that you need to request an ad hoc IP review in such a case.
Still, please keep in mind the following in mind, especially for future contributions: the tool of an ad hoc IP review should be used in extraordinary cases when it it is really not possible to remain under 1000 lines. I'd argue that the api implementation and the according tests could have been tailored and therefore contributed in multiple contributions but especially no TRG promotes huge contributions, they actually promote the contrary, for instance the documentation and the helm chart can be contributed in different pull requests, no TRG requires you otherwise.

Hi @borisrizov-zf, as product expert and committer besides @nitin-vavdiya, are you confident in reviewing this PR?

**Comment by borisrizov-zf** [comment]
@evegufy Yes, I'm aware of the size, but since @nitin-vavdiya  is a committer, the 1000 lines limit doesn't apply. The review is ongoing, I anticipate no issues to be honest since this code has been tested and used by Cofinity-X.

**Comment by evegufy** [comment]
> @evegufy Yes, I'm aware of the size, but since @nitin-vavdiya is a committer, the 1000 lines limit doesn't apply. The review is ongoing, I anticipate no issues to be honest since this code has been tested and used by Cofinity-X.

Hi @nitin-vavdiya @borisrizov-zf as you're contributing the developments to developers which are not committers, I''ll still recommend to initiate an IP review. I explained the process [here](https://github.com/eclipse-tractusx/ssi-dim-wallet-stub/pull/2#issuecomment-2284180573). Normally the Eclipse Foundation takes of IP reviews quite fast (if it's not in the midst of vacation season), I've seen some processed even within a day.

**Comment by nitin-vavdiya** [comment]
> > @evegufy Yes, I'm aware of the size, but since @nitin-vavdiya is a committer, the 1000 lines limit doesn't apply. The review is ongoing, I anticipate no issues to be honest since this code has been tested and used by Cofinity-X.
> 
> Hi @nitin-vavdiya @borisrizov-zf as you're contributing the developments to developers which are not committers, I''ll still recommend to initiate an IP review. I explained the process [here](https://github.com/eclipse-tractusx/ssi-dim-wallet-stub/pull/2#issuecomment-2284180573). Normally the Eclipse Foundation takes of IP reviews quite fast (if it's not in the midst of vacation season), I've seen some processed even within a day.

IP check issue created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16321

**Comment by nitin-vavdiya** [comment]
Separate issue created to fix Test and verify helm chart workflow: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/353

**Comment by nitin-vavdiya** [comment]
> > > @evegufy Yes, I'm aware of the size, but since @nitin-vavdiya is a committer, the 1000 lines limit doesn't apply. The review is ongoing, I anticipate no issues to be honest since this code has been tested and used by Cofinity-X.
> > 
> > 
> > Hi @nitin-vavdiya @borisrizov-zf as you're contributing the developments to developers which are not committers, I''ll still recommend to initiate an IP review. I explained the process [here](https://github.com/eclipse-tractusx/ssi-dim-wallet-stub/pull/2#issuecomment-2284180573). Normally the Eclipse Foundation takes of IP reviews quite fast (if it's not in the midst of vacation season), I've seen some processed even within a day.
> 
> IP check issue created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16321

@evegufy 
IP check is approved today, Is it okay to merge now?

**Comment by evegufy** [comment]
> > > > @evegufy Yes, I'm aware of the size, but since @nitin-vavdiya is a committer, the 1000 lines limit doesn't apply. The review is ongoing, I anticipate no issues to be honest since this code has been tested and used by Cofinity-X.
> > > 
> > > 
> > > Hi @nitin-vavdiya @borisrizov-zf as you're contributing the developments to developers which are not committers, I''ll still recommend to initiate an IP review. I explained the process [here](https://github.com/eclipse-tractusx/ssi-dim-wallet-stub/pull/2#issuecomment-2284180573). Normally the Eclipse Foundation takes of IP reviews quite fast (if it's not in the midst of vacation season), I've seen some processed even within a day.
> > 
> > 
> > IP check issue created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16321
> 
> @evegufy IP check is approved today, Is it okay to merge now?

sure

**Pull request merged**
