### PR TITLE
fix(helm): remove Helm release v1.1.0

### LINKED ISSUE #204: Remove v1.1.0 from chart index.yaml
Hello,

I am not sure why there is a release `v1.1.0` in the Helm releases:

https://github.com/eclipse-tractusx/managed-identity-wallet/blob/e7b2ae011b15f35e07d59b428c461fd8add7e0d9/index.yaml#L4-L41

Shouldn't that be removed because the new versioning is now at `v0.3.0`?

When searching for repos with Helm that might also lead to confusion:

```bash
$ helm search repo tractusx-dev/managed-identity-wallet --versions
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
tractusx-dev/managed-identity-wallet    1.1.0           0.0.1           Managed Identity Wallet is supposed to supply a...
tractusx-dev/managed-identity-wallet    0.3.0           0.3.0           Managed Identity Wallet is supposed to supply a...
```

<hr />

<sub>Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))</sub>

### PR DESCRIPTION
**Pull request by fty4**
## Description

Removing invalid release inside repo index.

fixes #204

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by borisrizov-zf** [comment]
@fty4 I believe you have to remove the archive file from the `helm-charts` directory.

**Comment by borisrizov-zf** [comment]
@fty4 Did you manually remove the entry or did you run `helm repo index helm-charts --url https://eclipse-tractusx.github.io/managed-identity-wallet/helm-charts`?

**Comment by fty4** [comment]
I manually removed the version and run the command afterwards - only had changes in the timestamp which I did not commit.

**Comment by fty4** [comment]
> @fty4 I believe the 1.1.0 version is already on the `tractusx-dev` repo, because I don't see it in the `helm-charts` directory. We'll have to remove it there too.

Which repo do you mean?
In the download address it is pointing to some release:
`https://github.com/eclipse-tractusx/managed-identity-wallet/releases/download/managed-identity-wallet-1.1.0/managed-identity-wallet-1.1.0.tgz`
But a release with this version is not present.

**Comment by borisrizov-zf** [comment]
> > @fty4 I believe the 1.1.0 version is already on the `tractusx-dev` repo, because I don't see it in the `helm-charts` directory. We'll have to remove it there too.
> 
> Which repo do you mean? In the download address it is pointing to some release: `https://github.com/eclipse-tractusx/managed-identity-wallet/releases/download/managed-identity-wallet-1.1.0/managed-identity-wallet-1.1.0.tgz` -> [managed-identity-wallet-1.1.0](https://github.com/eclipse-tractusx/managed-identity-wallet/releases/tag/managed-identity-wallet-1.1.0) should this be removed?

That should be removed as well. And the one on `eclipse-tractusx.github.io` too. Let's add a checklist to the summary so we can track everything that has to be removed.

**Comment by borisrizov-zf** [comment]
We'll be merging #208 and #209 first, afterwards we'll circle back to this.

**Comment by SebastianBezold** [comment]
To clarify our chart repo and publishing:

- Most of our repos publish charts via [chart-releaser-action](https://github.com/helm/chart-releaser-action)
- This packages the Helm Chart as `.tgz` and attaches it to a GitHub release, so it is downloadable
- Additionally a `index.yaml` with info about all released charts is maintained in the `gh-pages` branch
- Additionally to the stuff in a single repo, we do have a workflow, that is collection all of the `index.yaml` files from our repos and merges it to a single one in [eclipse-tractusx/charts](https://github.com/eclipse-tractusx/charts).
- This is is done to have a single Chart repo, that one can use to install all of our Charts and not having to add every GitHub repo as Chart repo

So to completely remove all traces of a Chart, we need to:

- delete the GitHub release containing the packaged Chart
- remove the reference to it in the index.yaml in the product repo
- remove the reference to it in the index.yaml in the  [eclipse-tractusx/charts](https://github.com/eclipse-tractusx/charts) repo

**Review by SebastianBezold — APPROVED** [review]

**Comment by fty4** [comment]
> So to completely remove all traces of a Chart, we need to:
> 
> * delete the GitHub release containing the packaged Chart
> * remove the reference to it in the index.yaml in the product repo
> * remove the reference to it in the index.yaml in the  [eclipse-tractusx/charts](https://github.com/eclipse-tractusx/charts) repo

@SebastianBezold Totally agree with you here.
I am not allowed to remove the release (point 1) but created this PR to remove the reference from the product repo (point 2).
I would have submitted a PR after this one is merged anyway in order to fix the charts repo reference.

@borisrizov-zf I do not understand why we need to wait for those two PRs - could you give more insights here?

**Comment by borisrizov-zf** [comment]
@fty4 Yes, our pipeline creates automatic releases, which means we'll need to rebase branches which are being PRed. The two commits are tightly coupled and I want them to go through uninterrupted. #208 is now merge and #209 will follow shortly. After that you can rebase and we can merge this PR.

**Comment by borisrizov-zf** [comment]
@fty4 Hi, you can rebase and force push. I will merge this then.

**Comment by fty4** [comment]
@borisrizov-zf I just updated the PR - please review.

I will now prepare a PR for [charts](https://github.com/eclipse-tractusx/charts).

**Review by borisrizov-zf — APPROVED** [review]

**Comment by fty4** [comment]
Who will delete the [release](https://github.com/eclipse-tractusx/managed-identity-wallet/releases/tag/managed-identity-wallet-1.1.0)?

**Comment by carslen** [comment]
> Who will delete the [release](https://github.com/eclipse-tractusx/managed-identity-wallet/releases/tag/managed-identity-wallet-1.1.0)?

✅

**Pull request merged**
