### PR TITLE
feat: Update GH Action workflow for Helm chart linting and tests

### PR DESCRIPTION
**Pull request by pmoscode**
## Description

This change updates the GH Action workflow to lint and test the Helm chart.

Test:
-> Helm unittests
-> Deploy on KinD cluster

Lint:
-> Chart Testing cli

It fixes also the dependency of external Docker images, because it spins up a KinD cluster on the agent and deploys the chart to it. With that, it checks, if the chart is deployable.

Fixes: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/51

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by pmoscode** [comment]
@mknoopvw @borisrizov-zf @DominikPinsel 
Please review.

**Comment by mknoopvw** [comment]
@pmoscode suits.
@SebastianBezold  this is follow-up PR for the chicken-egg-problem situation you helped us resolving yesterday.

**Comment by SebastianBezold** [comment]
HI @pmoscode, changes look good to me. Just a questing out of curiosity:

- Are there specific reasons/advantages, why you chose the `helm unit-test plugin` approach over the `ct` example provided in [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09)

**Comment by pmoscode** [comment]
> HI @pmoscode, changes look good to me. Just a questing out of curiosity:
> 
> * Are there specific reasons/advantages, why you chose the `helm unit-test plugin` approach over the `ct` example provided in [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09)

Hi @SebastianBezold, 
I follow two approaches:

- The use of unittest plugin to write unit tests like in Python, JavaScript, ... to have "static" tests of the Kubernetes resources
- Rely on the pod healthcheck (livenessProbe, readinessProbe) to ensure, the pod starts and is healthy

An additional overall API test will come in future. And then we may use "ct". 👍

**Pull request merged**
