### PR TITLE
fix:add if statement for creating VC to check expiration date

### PR DESCRIPTION
**Pull request by mustafasalfiti**
## Description

changing the current files by adding the if statement to check if there is an expiration date or not, it wont through an excpetion from Date.from(null)
or from date.toInstant()

#221 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by borisrizov-zf** [comment]
Hi, I think the implementation has to be changed to exclude the expirationDate from the Builder, if there is not date set. [Reference in W3C docs](https://www.w3.org/TR/vc-data-model/#expiration).

Also you'll have to do an interactive rebase to fix the commit text - there must be a space between `fix:` and the next word, e.g. `fix: blah blah`.

**Comment by mustafasalfiti** [comment]
I changed the commit name to include a space in between.

until now there is no problem with keeping expiry date, but we will be working in that in the future to include also the Lib

**Comment by mustafasalfiti** [comment]
> Hi, I think the implementation has to be changed to exclude the expirationDate from the Builder, if there is not date set. [Reference in W3C docs](https://www.w3.org/TR/vc-data-model/#expiration).
> 
> Also you'll have to do an interactive rebase to fix the commit text - there must be a space between `fix:` and the next word, e.g. `fix: blah blah`.



> Hi, I think the implementation has to be changed to exclude the expirationDate from the Builder, if there is not date set. [Reference in W3C docs](https://www.w3.org/TR/vc-data-model/#expiration).
> 
> Also you'll have to do an interactive rebase to fix the commit text - there must be a space between `fix:` and the next word, e.g. `fix: blah blah`.

I edited the commit name to include a space inbetween.
I think at this moment there is no problem to keep the expire date, we will have to take that into consideration as well for the SSI Lib

**Comment by borisrizov-zf** [comment]
Hm, I'm not sure, because it says:

> If present, the value of the expirationDate [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be a string value

That, for me at least, means thet having a `null` value is not acceptable.

**Comment by mustafasalfiti** [comment]
I think when its says ,,if present"" which is mean it can be null ?

**Comment by borisrizov-zf** [comment]
I read it as follows: "If **X** exists, then it must have a value of type string", meaning if the key is set, then the value must be a string. Null neither exists, nor is it a string. Please add it only conditionally and also rebase, as a critical pipeline update has been merged. 👍

**Comment by borisrizov-zf** [comment]
@mustafasalfiti ping.

**Comment by mustafasalfiti** [comment]
I rebased it with develop.

about the problem that the expire date will be set to null, at the end it will be handled from the SSI Lib and wont be added to the VC

this will explain the complete code flow 

https://github.com/eclipse-tractusx/SSI-agent-lib/pull/79/files

**Comment by borisrizov-zf** [comment]
I'll merge a fix for the pipeline and afterwards we can merge this.

**Comment by borisrizov-zf** [comment]
@mustafasalfiti you can rebase, the fix for the pipeline is merged.

**Comment by mustafasalfiti** [comment]
@borisrizov-zf  rebased

**Pull request merged**
