### PR TITLE
chore: update trivy.yml

### PR DESCRIPTION
**Pull request by the-tatanka**
Trivy pulls image from Docker Hub and scans image.

### CODE REVIEW

**Comment by pmoscode** [comment]
Hi @the-tatanka,
you have overwritten the local repo scan. 
Doesn't it make sense to scan - at least - both? (because of push trigger)

A Docker Hub scan would make sense, when an image was pushed via docker hub release workflow.
I would take care of this in the next few days.

What do you think?

Regards

**Comment by the-tatanka** [comment]
Hi @pmoscode , thanks for your feedback.
I removed the config scan and comments. The config scan does scan your IaC code - KICS also scans IaC and is better at it. So this scan is "doppelte Arbeit" / obsolete.
To scan the released image from docker hub is essential. 
In future I would like to scan the latest released image - an image with a latest tag.
In addition you scan the local docker image.

**Comment by pmoscode** [comment]
Hi @the-tatanka,
ok, I agree on KICS.

A few thoughts:
- In this case, there is no need for a "pull_request" (is already commented out) and "push" trigger. Scheduled and manual only should be fine.
- I personally prefer to pin components (in this case "actions") to a version to avoid unexpected behavior (e.g. breaking changes): aquasecurity/trivy-action@0.12.0

**Comment by the-tatanka** [comment]
@pmoscode I also prefer the pinned version. Is it @v0.12.0 or @0.12.0 - I'm not sure?
Official trivy doc recommends master, but anyway :)
I removed the push and pull request trigger.

**Comment by pmoscode** [comment]
aquasecurity/trivy-action@0.12.0 was the latest Release in their GH.

**Review by mknoopvw — APPROVED** [review]

**Review by pmoscode — APPROVED** [review]

**Pull request merged**
