### PR TITLE
fix(helm): use correct value for psql dependency condition

### PR DESCRIPTION
**Pull request by fty4**
## Description

Currently it seems that the wrong value key is referenced as dependency condition.

Changed to use following key:

https://github.com/eclipse-tractusx/managed-identity-wallet/blob/287b61d12cabf7e2a39f60e1f49d9baaa8401e8c/charts/managed-identity-wallet/values.yaml#L201-L204

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

<hr />

<sub>Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))</sub>

### CODE REVIEW

**Comment by borisrizov-zf** [comment]
@fty4 please rebase, force push and we can merge.

**Comment by fty4** [comment]
@borisrizov-zf I've fixed the merge conflict

**Comment by borisrizov-zf** [comment]
@fty4 One last thing. Can you run the following and add the changed files to a commit:

```bash
cd charts/managed-identity-wallet
helm dependency update
```

**Comment by borisrizov-zf** [comment]
@fty4 Last one I promise 😆 

```bash
# in project root
task helm:readme

# or if you don't have task installed
cd charts/managed-identity-wallet
helm-docs -I charts/managed-identity-wallet/.helmdocsignore .
```

We're going to automate this in a future release, but for the time-being it's still necessary.

**Comment by fty4** [comment]
I just saw that and checked the diff which is huge..
Shouldn't that be added in another PR?

```diff
diff --git a/charts/managed-identity-wallet/README.md b/charts/managed-identity-wallet/README.md
index 5a24daad..20f80870 100644
--- a/charts/managed-identity-wallet/README.md
+++ b/charts/managed-identity-wallet/README.md
@@ -2,7 +2,7 @@
 
 # managed-identity-wallet
 
-![Version: 0.4.0-develop.2](https://img.shields.io/badge/Version-0.4.0--develop.2-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: 0.4.0-develop.2](https://img.shields.io/badge/AppVersion-0.4.0--develop.2-informational?style=flat-square)
+![Version: 0.4.0-develop.3](https://img.shields.io/badge/Version-0.4.0--develop.3-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: 0.4.0-develop.3](https://img.shields.io/badge/AppVersion-0.4.0--develop.3-informational?style=flat-square)
 
 Managed Identity Wallet is supposed to supply a secure data source and data sink for Digital Identity Documents (DID), in order to enable Self-Sovereign Identity founding on those DIDs.
 And at the same it shall support an uninterrupted tracking and tracing and documenting the usage of those DIDs, e.g. within logistical supply chains.
diff --git a/charts/managed-identity-wallet/charts/pgadmin4/README.md b/charts/managed-identity-wallet/charts/pgadmin4/README.md
index 7a3aa7b8..301bb492 100644
--- a/charts/managed-identity-wallet/charts/pgadmin4/README.md
+++ b/charts/managed-identity-wallet/charts/pgadmin4/README.md
@@ -1,137 +1,93 @@
-###### based on [dpage/pgadmin4]
-
-# pgAdmin 4
-
-[pgAdmin4](https://www.pgadmin.org/) is the leading Open Source management tool for Postgres, the world’s most advanced Open Source database. pgAdmin4 is designed to meet the needs of both novice and experienced Postgres users alike, providing a powerful graphical interface that simplifies the creation, maintenance and use of database objects.
-
-## TL;DR;
-
-```console
-helm repo add runix https://helm.runix.net
-helm install runix/pgadmin4
-```
-
-## Introduction
-
-This chart bootstraps a [pgAdmin4](https://www.pgadmin.org/) deployment on a [Kubernetes](http://kubernetes.io) cluster using the [Helm](https://helm.sh) package manager.
-
-## Install the Chart
-
-To install the chart with the release name `my-release`:
-
-```console
-$ # Helm 2
-helm install --name my-release runix/pgadmin4
-$ # Helm 3
-helm install my-release runix/pgadmin4
-```
-
-The command deploys pgAdmin4 on the Kubernetes cluster in the default configuration. The configuration section lists the parameters that can be configured during installation.
-
-> **Tip**: List all releases using `helm list`
-
-## Uninstall the Chart
-
-To uninstall/delete the `my-release` deployment:
-
-```console
-helm delete --purge my-release
-```
-
-The command removes nearly all the Kubernetes components associated with the chart and deletes the release.
-
-## Configuration
-
-| Parameter | Description | Default |
-| --------- | ----------- | ------- |
-| `replicaCount` | Number of pgadmin4 replicas | `1` |
-| `image.registry` | Docker image registry | `docker.io` |
-| `image.repository` | Docker image | `dpage/pgadmin4` |
-| `image.tag` | Docker image tag | `""` |
-| `image.pullPolicy` | Docker image pull policy | `IfNotPresent` |
-| `annotations` | Deployment Annotations | `{}` |
-| `priorityClassName` | Deployment priorityClassName | `""` |
-| `command` | Deployment command override | `""` |
-| `service.type` | Service type (ClusterIP, NodePort or LoadBalancer) | `ClusterIP` |
-| `service.clusterIP` | Service type Cluster IP | `""` |
-| `service.loadBalancerIP` | Service Load Balancer IP | `""` |
-| `service.annotations` | Service Annotations | `{}` |
-| `service.port` | Service port | `80` |
-| `service.portName` | Name of the port on the service | `http` |
-| `service.targetPort` | Internal service port | `http` |
-| `service.nodePort` | Kubernetes service nodePort | `` |
-| `serviceAccount.create` | Creates a ServiceAccount for the pod. | `false` |
-| `serviceAccount.annotations` | Annotations to add to the service account. | `{}` |
-| `serviceAccount.name` | The name of the service account. Otherwise uses the fullname. | `` |
-| `serviceAccount.automountServiceAccountToken` | Opt out of API credential automounting. | `false` |
-| `strategy` | Specifies the strategy used to replace old Pods by new ones | `{}` |
-| `ingress.enabled` | Enables Ingress | `false` |
-| `ingress.annotations` | Ingress annotations | `{}` |
-| `ingress.ingressClassName` | Ingress class name | `""` |
-| `ingress.hosts.host` | Ingress accepted hostname | `nil` |
-| `ingress.hosts.paths` | Ingress paths list | `[]` |
-| `ingress.tls` | Ingress TLS configuration | `[]` |
-| `extraConfigmapMounts` | Additional configMap volume mounts for pgadmin4 pod | `[]` |
-| `extraSecretMounts` | Additional secret volume mounts for pgadmin4 pod | `[]` |
-| `extraContainers` | Sidecar containers to add to the pgadmin4 pod  | `"[]"` |
-| `existingSecret` | The name of an existing secret containing the pgadmin4 default password. | `""` |
-| `secretKeys.pgadminPasswordKey` | Name of key in existing secret to use for default pgadmin credentials. Only used when `existingSecret` is set. | `"password"` |
-| `extraInitContainers` | Sidecar init containers to add to the pgadmin4 pod  | `"[]"` |
-| `env.email` | pgAdmin4 default email. Needed chart reinstall for apply changes | `chart@domain.com` |
-| `env.password` | pgAdmin4 default password. Needed chart reinstall for apply changes | `SuperSecret` |
-| `env.pgpassfile` | Path to pgpasssfile (optional). Needed chart reinstall for apply changes | `` |
-| `env.enhanced_cookie_protection` | Allows pgAdmin4 to create session cookies based on IP address | `"False"` |
-| `env.contextPath` | Context path for accessing pgadmin (optional) | `` |
-| `envVarsFromConfigMaps` | Array of ConfigMap names to load as environment variables | `[]` |
-| `envVarsFromSecrets` | Array of Secret names to load as environment variables | `[]` |
-| `persistentVolume.enabled` | If true, pgAdmin4 will create a Persistent Volume Claim | `true` |
-| `persistentVolume.accessMode` | Persistent Volume access Mode | `ReadWriteOnce` |
-| `persistentVolume.size` | Persistent Volume size | `10Gi` |
-| `persistentVolume.storageClass` | Persistent Volume Storage Class | `unset` |
-| `persistentVolume.existingClaim` | Persistent Volume existing claim name | | `unset` |
-| `persistentVolume.subPath` | Subdirectory of the volume to mount at | `unset` |
-| `securityContext` | Custom [pod security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) for pgAdmin4 pod | `` |
-| `containerSecurityContext` | Custom [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) for pgAdmin4 container | `` |
-| `livenessProbe` | [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) initial delay and timeout | `` |
-| `startupProbe` | [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) initial delay and timeout | `` |
-| `readinessProbe` | [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) initial delay and timeout | `` |
-| `VolumePermissions.enabled` | Enables init container that changes volume permissions in the data directory  | `false` |
-| `extraInitContainers` | Init containers to launch alongside the app | `[]` |
-| `containerPorts.http` | Sets http port inside pgadmin container | `80` |
-| `resources` | CPU/memory resource requests/limits | `{}` |
-| `nodeSelector` | Node labels for pod assignment | `{}` |
-| `tolerations` | Node tolerations for pod assignment | `[]` |
-| `affinity` | Node affinity for pod assignment | `{}` |
-| `podAnnotations` | Annotations for pod | `{}` |
-| `podLabels` | Labels for pod | `{}` |
-| `namespace` | Namespace where to deploy resources | `null` |
-| `init.resources` | Init container CPU/memory resource requests/limits | `{}` |
-
-> The values for "extraConfigmapMounts.[].configMap" and "extraSecretMounts.[].secret" can be either a simple string
-> or a template string.
-> Then it will be resolved for you.
-
-Specify each parameter using the `--set key=value[,key=value]` argument to `helm install`. For example:
-
-```console
-$ # Helm 2
-helm install runix/pgadmin4 --name my-release \
-  --set env.password=SuperSecret
-$ # Helm 3
-helm install my-release runix/pgadmin4 \
-  --set env.password=SuperSecret
-```
-
-Alternatively, a YAML file that specifies the values for the parameters can be
-provided while installing the chart. For example:
-
-```console
-$ # Helm 2
-helm install runix/pgadmin4 --name my-release -f values.yaml
-$ # Helm 3
-helm install my-release runix/pgadmin4 -f values.yaml
-```
-
-> **Tip**: You can use the default [values.yaml](https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/values.yaml) and look on [examples](https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/examples/).
-
-[dpage/pgadmin4]: https://hub.docker.com/r/dpage/pgadmin4
+# pgadmin4
+
+![Version: 1.19.0](https://img.shields.io/badge/Version-1.19.0-informational?style=flat-square) ![AppVersion: 7.8](https://img.shields.io/badge/AppVersion-7.8-informational?style=flat-square)
+
+pgAdmin4 is a web based administration tool for PostgreSQL database
+
+**Homepage:** <https://www.pgadmin.org/>
+
+## Maintainers
+
+| Name | Email | Url |
+| ---- | ------ | --- |
+| rowanruseler | <rowanruseler@gmail.com> |  |
+
+## Source Code
+
+* <https://github.com/rowanruseler/helm-charts>
+
+## Values
+
+| Key | Type | Default | Description |
+|-----|------|---------|-------------|
+| VolumePermissions.enabled | bool | `false` |  |
+| affinity | object | `{}` |  |
+| annotations | object | `{}` |  |
+| containerPorts.http | int | `80` |  |
+| containerSecurityContext.allowPrivilegeEscalation | bool | `false` |  |
+| containerSecurityContext.enabled | bool | `false` |  |
+| env.email | string | `"chart@domain.com"` |  |
+| env.enhanced_cookie_protection | string | `"False"` |  |
+| env.password | string | `"SuperSecret"` |  |
+| env.variables | list | `[]` |  |
+| envVarsFromConfigMaps | list | `[]` |  |
+| envVarsFromSecrets | list | `[]` |  |
+| existingSecret | string | `""` |  |
+| extraConfigmapMounts | list | `[]` |  |
+| extraContainers | string | `""` |  |
+| extraInitContainers | string | `""` |  |
+| extraSecretMounts | list | `[]` |  |
+| extraVolumeMounts | list | `[]` |  |
+| extraVolumes | list | `[]` |  |
+| image.pullPolicy | string | `"IfNotPresent"` |  |
+| image.registry | string | `"docker.io"` |  |
+| image.repository | string | `"dpage/pgadmin4"` |  |
+| image.tag | string | `""` |  |
+| ingress.annotations | object | `{}` |  |
+| ingress.enabled | bool | `false` |  |
+| ingress.hosts[0].host | string | `"chart-example.local"` |  |
+| ingress.hosts[0].paths[0].path | string | `"/"` |  |
+| ingress.hosts[0].paths[0].pathType | string | `"Prefix"` |  |
+| ingress.tls | list | `[]` |  |
+| init.resources | object | `{}` |  |
+| livenessProbe.failureThreshold | int | `3` |  |
+| livenessProbe.initialDelaySeconds | int | `30` |  |
+| livenessProbe.periodSeconds | int | `60` |  |
+| livenessProbe.successThreshold | int | `1` |  |
+| livenessProbe.timeoutSeconds | int | `15` |  |
+| namespace | string | `nil` |  |
+| nodeSelector | object | `{}` |  |
+| persistentVolume.accessModes[0] | string | `"ReadWriteOnce"` |  |
+| persistentVolume.annotations | object | `{}` |  |
+| persistentVolume.enabled | bool | `true` |  |
+| persistentVolume.size | string | `"10Gi"` |  |
+| podAnnotations | object | `{}` |  |
+| podLabels | object | `{}` |  |
+| priorityClassName | string | `""` |  |
+| readinessProbe.failureThreshold | int | `3` |  |
+| readinessProbe.initialDelaySeconds | int | `30` |  |
+| readinessProbe.periodSeconds | int | `60` |  |
+| readinessProbe.successThreshold | int | `1` |  |
+| readinessProbe.timeoutSeconds | int | `15` |  |
+| replicaCount | int | `1` |  |
+| resources | object | `{}` |  |
+| secretKeys.pgadminPasswordKey | string | `"password"` |  |
+| securityContext.fsGroup | int | `5050` |  |
+| securityContext.runAsGroup | int | `5050` |  |
+| securityContext.runAsUser | int | `5050` |  |
+| service.annotations | object | `{}` |  |
+| service.clusterIP | string | `""` |  |
+| service.loadBalancerIP | string | `""` |  |
+| service.port | int | `80` |  |
+| service.portName | string | `"http"` |  |
+| service.targetPort | int | `80` |  |
+| service.type | string | `"ClusterIP"` |  |
+| serviceAccount.annotations | object | `{}` |  |
+| serviceAccount.automountServiceAccountToken | bool | `false` |  |
+| serviceAccount.create | bool | `false` |  |
+| serviceAccount.name | string | `""` |  |
+| strategy | object | `{}` |  |
+| tolerations | list | `[]` |  |
+
+----------------------------------------------
+Autogenerated from chart metadata using [helm-docs v1.11.3](https://github.com/norwoodj/helm-docs/releases/v1.11.3)
```

**Comment by borisrizov-zf** [comment]
> I just saw that and checked the diff which is huge.. Shouldn't that be added in another PR?
> 
> diff

Ah, I see. I had the same issue. can you checkout the last `develop` and run the command again? If it works, then you'll probably have to check if the merge didn't throw out the `.helmdocsignore`. As a last resort you can rebase instead of merging `develop`. I'm available for a quick call if you want a second set of eyes on that.

**Comment by borisrizov-zf** [comment]
@fty4 
I tried the command on your branch, it worked for me. Please try to run it in the `charts/managed-identity-wallet` directory:

```bash
helm-docs -i charts/managed-identity-wallet/.helmdocsignore .
```

The helm-docs command will traverse the dir-tree back to the project root, where the `-I` parameter will be applied. Otherwise you'll pick up on the `README.md` in the `charts/managed-identity-wallet/charts/pgadmin4` directory.

**Comment by fty4** [comment]
I was a little bit confused about your command - I thought it was a mistake because the path did not exist if you are inside the `charts/managed-identity-wallet` directory.
Because of that I used the following command which also updated the pgadmin chart...:

```bash
helm-docs -i .helmdocsignore .
```

Now only the miw _README.md_ is updated.

**Pull request merged**
