### PR TITLE
chore: merge main to develop

### PR DESCRIPTION
**Pull request by DominikPinsel**
Just a merge from main to develop. Please ignore the size.

Additional Commits:
+ added one liner to fix failing tests
+ disabled docker-hub-release.yaml

### CODE REVIEW

**Review by borisuu — APPROVED** [review]
As we spoke, this is necessary to bring the 'develop' branch to the same code level as the main branch (some fixes were merged directly into main during the last release).

**Comment by carslen** [comment]
There is still one test failing. Could you take a look again @DominikPinsel ?

**Comment by DominikPinsel** [comment]
> There is still one test failing. Could you take a look again @DominikPinsel ?

Will do :) The never ran successfully, but I will repair it anyway.

**Comment by DominikPinsel** [comment]
@carslen Disabled the workflow, it never ran. It can be merged now :)

**Comment by borisrizov-zf** [comment]
Ping @carslen

**Pull request merged**
