### PR TITLE
chore: update SECURITY.md

### PR DESCRIPTION
**Pull request by pablosec**
## Description

Make SECURITY.md reflect current example of [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01#security-file) pointing to the GitHub Security Tab instead of directly to Eclipse

## Pre-review checks

not applicable

### CODE REVIEW

**Comment by borisrizov-zf** [comment]
@pablosec please edit the PR to point at the 'develop' branch.

**Comment by pablosec** [comment]
@borisrizov-zf done. But I don’t fully understand, how the two other commits, not related to SECURITY.md, got into this PR...?

**Comment by borisrizov-zf** [comment]
@pablosec We use a bot for semantic releases and it adds some CHANGELOG stuff and updates the main Helm chart.

**Comment by borisrizov-zf** [comment]
@pablosec can you rebase, I've merged some other branches and now there are conflicts. Thanks!

**Pull request closed without merging**
