### PR TITLE
feat: validate issuer bpn while creating new wallet,  random Key Reference to DID, delete API removed, did document resolver component, ssi lib version update

### PR DESCRIPTION
**Pull request by nitin-vavdiya**
Tasks covered: 

1. Base/authority wallet check along with the role check added in create wallet API. Previously it was only checking the `add_wallets` role. Due to these changes, we have to modify almost every test case which involves creating a wallet part

2. Random UUID added as key reference in verification method of did document. This will help when we start adding multiple key/multiple verification methods in did document 

i.e.
```
{
  "@context":
  [
      "https://www.w3.org/ns/did/v1",
      "https://w3c.github.io/vc-jws-2020/contexts/v1"
  ],
  "id": "did:web:localhost:BPNL000000000001",
  "verificationMethod":
  [
      {
          "controller": "did:web:localhost:BPNL000000000001",
          "id": "did:web:localhost:BPNL000000000001#cab83a66-031c-4924-a268-4c899e1c26d3",  //key reference after #
          "publicKeyJwk":
          {
              "crv": "Ed25519",
              "kty": "OKP",
              "x": "mhph0ZSVk7cDVmazbaaC3jBDpphW4eNygAK9gHPlMow"
          },
          "type": "JsonWebKey2020"
      }
  ]
}
```
3.  Delete credential by credential ID API is removed as per feedback from stakeholder

4. In ssi-lib, There is an update regarding did resolver component and according to this change, we need to modify the code of create, validate credentials and presentation. Please refer to [these changes](https://github.com/catenax-ng/product-lab-ssi/pull/114) for more information. 

5. ssi-lib version updated to `0.0.15`

### CODE REVIEW

**Comment by mknoopvw** [comment]
This PR contains our most recent source code concerning:
- updated dependencies
- features
- fixes of faults

It sound against the three item stated above.

@borisrizov-zf if there are no objections from your point of view, please, confirm so that this PR may be merged in order to be part of the RCs and the release then.

**Comment by SebastianBezold** [comment]
Hi @nitin-vavdiya and @mknoopvw,

Before accepting this change, I would love to see a better PR description. Meaning no links to closed systems describing the changes, but openly describe it, so the whole open-source community can follow what's going on.

Also the screenshots do not really add value. Although I trust you on this one, screenshots could come from anywhere. So if the unit tests are not yet included as PR checks, you can just skip that info. As soon as the unit tests are executed on each PR, you do have the reliable info present as check directly in the check area of the PR.

For this PR, it would be ok to add info from all of the tickets you linked to the PR description.
For upcomming PRs I would actually appreciate if different features are split to different PRs. Merging PRs on forks and then doing "sync" PRs is maybe fine for the next couple of days to get the release done, but not a good way forward. -> Harder to review. Longer "hidden" work, where outside contributors do have a harder time to follow

**Review by borisrizov-zf — COMMENTED** [review]
it seems the version of cx-ssi-lib:0.0.15 doesn't include `DidWebResolver` & `DidResolver`. Only `DidWebDocumentResolver` and `DidDocumentResolver`.

The `ssi.lib.proof.LinkedDataProofValidation` class has a typo in the method name `verifiyProof`, but you've used `verifyProof`.

The `LinkedDataProofValidation.newInstance` method expects the second argument to be `DidDocumentResolverRegistry`, and has to be cast.

**Comment by nitin-vavdiya** [comment]
Thanks @SebastianBezold  for the great input.
PR description updated and I completely agree that it is very difficult to review this kind of "sync" PR as they become very bulky. Next time We will create pull requests for individual tasks/features.

**Comment by borisrizov-zf** [comment]
@SebastianBezold we have two options:
1. merge develop into main (cx-ssi-lib repo), create a new release 0.0.16 containing the missing source files and update the version in this PR.
2. revert the part of the commit which uses the missing sources and defer to the next release cycle.

I think option 2 is the better solution for right now.

**Comment by nitin-vavdiya** [comment]
@borisrizov-zf @SebastianBezold 
Changes are reverted.

**Comment by borisrizov-zf** [comment]
Let's merge and continue @SebastianBezold

**Pull request merged**
