### PR TITLE
feat: Version upgrade of libs : CGD-457

### PR DESCRIPTION
**Pull request by nitin-vavdiya**
Version upgraded for below libs:

1. Spring boot
2. Spring Cloud
3. commons-dao
4. json
5. Jacoco
6. Spring API doc

Fix: The new version of keycloak test container returns the hostname without trailing "/"

### CODE REVIEW

**Comment by SebastianBezold** [comment]
HI @nitin-vavdiya,

when 3rd party dependencies are updated, the information in the `DEPENDENCIES` file also needs to be up-to-date. Could you please regenerate the fiel with the [Dash License tool](https://github.com/eclipse/dash-licenses) If the log output indicates, that there is IP review necessary, I can open the automated issue for you. Just give me a ping in this case

**Comment by nitin-vavdiya** [comment]
@SebastianBezold 
DEPENDENCIES file has been regenerated.

**Comment by SebastianBezold** [comment]
With the dependency list for Dash input provided by @mknoopvw, I could create automated IP issues.
There was some invalid Input mentioned by Dash, so I'm not sure if it is complete. I'll investigate later.
The IP issues created are:

- [maven/mavencentral/org.json/json/20230618](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10220)
- [maven/mavencentral/org.webjars/swagger-ui/5.2.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10221)
- [maven/mavencentral/com.github.dasniko/testcontainers-keycloak/3.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10222)
- [maven/mavencentral/org.jboss.resteasy/resteasy-client-api/6.2.4.Final](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10223)

Please keep an eye on that issues and regenerate the DEPENDENCIES file again, as soon as the issues are approved.
In some cases there could also be a "Help wanted" label on the issues, in case the EF IP team needs assistance from you to clarify the scope of usage for the library

**Comment by nitin-vavdiya** [comment]
@SebastianBezold 
Only one issue is Open now which is for org.json:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10220

**Comment by nitin-vavdiya** [comment]
@SebastianBezold 
JSON is resolved now. 
There 2 dependencies with  restricted

`maven/mavencentral/com.fasterxml.jackson.jakarta.rs/jackson-jakarta-rs-base/2.14.3, , restricted, clearlydefined
`
`maven/mavencentral/com.fasterxml.jackson.jakarta.rs/jackson-jakarta-rs-json-provider/2.14.3, , restricted, clearlydefined
`

**Comment by nitin-vavdiya** [comment]
Not needed now

**Pull request closed without merging**
