### PR TITLE
feat(ssi): add revocation service, DCP changes and trufflehog workflow

### PR DESCRIPTION
**Pull request by nitin-vavdiya**
## Description

1. VC revocation service added
2. Truffelhog workflow added
3. VC/VP issued as JWT by default 
4. Base controller is removed and direct access to Spring security principle in controllers is removed
5. Did document update to comply with DCP flow 
6. Query presentation API changes as per DCP specification

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by matbmoser — CHANGES_REQUESTED** [review]
I don't see any IP check open for  this  ticket.
The "--only-verified" can be  included to reduce the false positives, not sure of its impact,  @RoKrish14 do you  know  something about this in more deep as me?

**Review by evegufy — COMMENTED** [review]
Just some comments:

Some of the warnings from KICS are TRG relevant:
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07
if you don't address them directly please create issues to make that trasparent.

IATP is since quite a while called [DCP](https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol), I'd update the PR title and description accordingly

PR title could be improved in regards of conventional commits:
- the scope doesn't quite fit --> it's not just about revocation, I think ssi (for Self-Sovereign Identity) would be more fitting
- typo in trufflehog
- no use of imperative
`feat(ssi): add revocation service, DCP changes and trufflehog workflow` would be more fitting IMO

**Comment by RoKrish14** [comment]
> I don't see any IP check open for this ticket. The "--only-verified" can be included to reduce the false positives, not sure of its impact, @RoKrish14 do you know something about this in more deep as me?

Hey @matbmoser :
I have added 4 flags for TruffleHog scan to have optimized results (lesser FP)

-> **--filter-entropy=4** ensures you're only detecting high-entropy strings that are more likely to be real secrets
-> **--results=verified,unknown** flag includes both confirmed and suspicious secrets
-> **--debug** flag enables debug-level logging, providing additional details about the internal workings of TruffleHog during the scan.
-> **--only-verified** flag narrows down the findings to only verified secrets. **Impact**: ensures that both high-confidence findings and ambiguous results are included in the output

This combination offers a better overview of results and avoid unnecessary False Positives.

**Comment by matbmoser** [comment]
> > I don't see any IP check open for this ticket. The "--only-verified" can be included to reduce the false positives, not sure of its impact, @RoKrish14 do you know something about this in more deep as me?
> 
> Hey @matbmoser : I have added 4 flags for TruffleHog scan to have optimized results (lesser FP)
> 
> -> **--filter-entropy=4** ensures you're only detecting high-entropy strings that are more likely to be real secrets -> **--results=verified,unknown** flag includes both confirmed and suspicious secrets -> **--debug** flag enables debug-level logging, providing additional details about the internal workings of TruffleHog during the scan. -> **--only-verified** flag narrows down the findings to only verified secrets. **Impact**: ensures that both high-confidence findings and ambiguous results are included in the output
> 
> This combination offers a better overview of results and avoid unnecessary False Positives.


@RoKrish14 super! Thank you for the support and the quick reply!

**Comment by nitin-vavdiya** [comment]
> Some of the warnings from KICS are TRG relevant:
> https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04
> https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03
> https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07

Issue created to fix TRGs: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/359

PR title and description updated

**Comment by matbmoser** [comment]
Where was the IP check ticket for this PR? @evegufy, @stephanbcbauer  and @tom-rm-meyer-ISST is this not a requirement for PRs with 12.000 lines of code?

**Comment by tom-rm-meyer-ISST** [comment]
> Where was the IP check ticket for this PR? @evegufy, @stephanbcbauer and @tom-rm-meyer-ISST is this not a requirement for PRs with 12.000 lines of code?

Nitin is a [committer](https://projects.eclipse.org/projects/automotive.tractusx/who) and thus an IP check is not necessarily needed as we consider him to work clean in that regard. That applies to Nitin, not to all contributions in this branch (likely due to merges)

Just from seing the klocs and multiple persons involved, I would have requested an IP check TBH. Not because I don't trust my colleagues but to be sure that everythin is fine.

**Comment by nitin-vavdiya** [comment]
@tom-rm-meyer-ISST @matbmoser 

Thank you for reviewing this PR.

In this repository, our process involves using the `develop` branch as a staging branch, where we merge all new features before a release. Once ready for release, we then merge `develop` into the `main` branch, per the guidelines outlined in our [contribution documentation](https://github.com/eclipse-tractusx/managed-identity-wallet/blob/main/CONTRIBUTING.md#for-eclipse-committers-and-maintainers).

The same thing is done also in the past: https://github.com/eclipse-tractusx/managed-identity-wallet/pull/320

This PR introduces the revocation service feature(~10K lines of changes), and we have completed an IP check for this feature as part of merging it into the `develop` branch. 

Ref: 
https://github.com/eclipse-tractusx/managed-identity-wallet/pull/317
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16321

However, if there’s consensus that an additional IP check should still be conducted for this PR, could you please guide us on the recommended steps to proceed at this stage?

Thank you for your attention and guidance.

**Comment by tom-rm-meyer-ISST** [comment]
> @tom-rm-meyer-ISST @matbmoser
> 
> Thank you for reviewing this PR.
> 
> In this repository, our process involves using the `develop` branch as a staging branch, where we merge all new features before a release. Once ready for release, we then merge `develop` into the `main` branch, per the guidelines outlined in our [contribution documentation](https://github.com/eclipse-tractusx/managed-identity-wallet/blob/main/CONTRIBUTING.md#for-eclipse-committers-and-maintainers).
> 
> The same thing is done also in the past: #320
> 
> This PR introduces the revocation service feature(~10K lines of changes), and we have completed an IP check for this feature as part of merging it into the `develop` branch.
> 
> Ref: #317 https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16321
> 
> However, if there’s consensus that an additional IP check should still be conducted for this PR, could you please guide us on the recommended steps to proceed at this stage?
> 
> Thank you for your attention and guidance.

@nitin-vavdiya Ah thanks, wans't patient that you already merged into the Eclipse Tractus-X develop branch. The guideline of the EF refers to code getting into the Eclipse Tractus-X. As you're already creating the IP issues when everything gets into the develop branch in the EF repo, it's accurate practice.

Having a second IP check would be inappropriate. Thanks for claryfying! :)

Actually I thought about doing something similar for our repo with feature branches, where I can do IP checks of contributors when merging into the EF repo and then we can review and refactor the feature as a whole when all parts are given. Result would be smaller chunks of IP check and only merging fully developed features into main.

**Pull request merged**
