### PR TITLE
fix: run scan once a day, renamed veracode project

### PR DESCRIPTION
**Pull request by the-tatanka**
@mknoopvw please check build, see https://github.com/eclipse-tractusx/managed-identity-wallet/actions/runs/5521848469/jobs/10070563055
Your build is not working.

### CODE REVIEW

**Comment by the-tatanka** [comment]
@mknoopvw

**Comment by mknoopvw** [comment]
Working on it. We have to see what's wrong there: new repos, actions, all the fancy things to configure....

**Comment by the-tatanka** [comment]
no problem, it's okay. I just wanted you to see it

**Comment by pmoscode** [comment]
This PR is obsolete, because it's already merged with PR https://github.com/eclipse-tractusx/managed-identity-wallet/pull/38/files#diff-76296b7fe783601e3b0d1057050d4c4a6144b80e80a751f74bf87932bce58b41

**Comment by DominikPinsel** [comment]
@the-tatanka Is it ok for you if we close this PR?

**Pull request closed without merging**
